---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: issuers.cert.gardener.cloud
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-cert-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.acme.server
      description: ACME Server
      name: SERVER
      type: string
    - JSONPath: .spec.acme.email
      description: ACME Registration email
      name: EMAIL
      type: string
    - JSONPath: .status.state
      description: Status of registration
      name: STATUS
      type: string
    - JSONPath: .status.type
      description: Issuer type
      name: TYPE
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: AGE
      type: date
  conversion:
    strategy: None
  group: cert.gardener.cloud
  names:
    kind: Issuer
    listKind: IssuerList
    plural: issuers
    shortNames:
      - issuer
    singular: issuer
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Issuer is the issuer CR.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: IssuerSpec is the spec of the issuer.
          properties:
            acme:
              description: ACME is the ACME protocol specific spec.
              properties:
                autoRegistration:
                  description: AutoRegistration is the flag if automatic registration
                    should be applied if needed.
                  type: boolean
                email:
                  description: Email is the email address to use for user registration.
                  type: string
                privateKeySecretRef:
                  description: PrivateKeySecretRef is the secret ref to the ACME private
                    key.
                  properties:
                    name:
                      description: Name is unique within a namespace to reference
                        a secret resource.
                      type: string
                    namespace:
                      description: Namespace defines the space within which the secret
                        name must be unique.
                      type: string
                  type: object
                server:
                  description: Server is the URL of the ACME server.
                  type: string
              required:
                - email
                - server
              type: object
          type: object
        status:
          description: IssuerStatus is the status of the issuer.
          properties:
            acme:
              description: ACME is the ACME specific status.
              type: object
            message:
              description: Message is the status or error message.
              type: string
            observedGeneration:
              description: ObservedGeneration is the observed generation of the spec.
              format: int64
              type: integer
            state:
              description: State is either empty, 'Pending', 'Error', or 'Ready'.
              type: string
            type:
              description: Type is the issuer type. Currently only 'acme' is supported.
              type: string
          required:
            - state
            - type
          type: object
      required:
        - spec
      {{- if semverCompare ">= 1.12" .Capabilities.KubeVersion.GitVersion }}
      type: object
      {{- end }}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
