apiVersion: {{ include "priorityclassversion" . }}
kind: PriorityClass
metadata:
  name: gardener-extension-shoot-cert-service
value: 1000000000
globalDefault: false
description: "Priority class for the Gardener extension: shoot-cert-service."