---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extensions.gardener.cloud:extension-shoot-cert-service:cert-controller-manager
  namespace: {{ .Release.Namespace }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gardener.cloud:system:cert-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extensions.gardener.cloud:extension-shoot-cert-service:cert-controller-manager
